version: "3.9"

services:
  api:
    build: .
    container_name: todoapi
    ports:
      - "5000:8080"
    depends_on:
      - db
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tododb
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

